import logging

from gameart.draw import art
from gameart.inputs import keylogger, mousetracker

logging.basicConfig(level=logging.INFO)


def record_keyboard() -> None:
    """
    Public function to start recording of keyboard input
    """
    keylogger._record()


def record_mouse() -> None:
    """
    Public function to start recording of mouse input
    """
    mousetracker._record()


def draw_dots() -> None:
    """
    Public function to draw dot-art based on csv file input which was
    generated by the method 'record_keyboard'
    """
    art._draw_dots()


def draw_lines() -> None:
    """
    Public function to draw line-art based on csv file input which was
    generated by the method 'record_keyboard'
    """
    art._draw_lines()


def draw_mouse_tracks() -> None:
    """
    Public function to draw mousetracking-art based on csv file input
    which was generated by the method 'record_mouse'
    """
    art._draw_mouse_tracks()
