import logging

from gameart.draw import art
from gameart.inputs import mousetracker

logging.basicConfig(level=logging.INFO)


def record_mouse() -> None:
    """
    Public function to start recording of mouse input
    """
    mousetracker._record_mouse()


def draw_mouse_tracks() -> None:
    """
    Public function to draw mousetracking-art based on csv file input
    which was generated by the method 'record_mouse'
    """
    art._draw_mouse_tracks()
