name: Python package

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Create Virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install dependencies
      run: |
        python -m pip install .[release]

    - run: pyinstaller --onefile .\src\gameart\gui.py --icon .\images\logo.png
    - uses: actions/upload-artifact@v3
      with:
        path: dist/*

    - name: Get version
      uses: maybe-hello-world/pyproject-check-version@v4
      id: getversion
      with:
        pyproject-path: "./pyproject.toml"

    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.head_commit.message }}
        release_name: ${{ github.event.head_commit.message }}
        body: |
          GameArt ${{ steps.getversion.outputs.local_version }}
        draft: false
        prerelease: false
