name: Publish to PyPi and upload executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  PyInstaller:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest']
        include:
          - os: 'windows-latest'
            activate: 'env\Scripts\activate'
          - os: 'ubuntu-latest'
            activate: 'source env/bin/activate'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Create virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        ${{ matrix.activate }}
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install dependencies
      run: |
        python -m pip install .[release]

    - run: pyinstaller --onefile ./src/gameart/gui.py --icon ./images/logo.png --distpath ./dist_exe --name gameart
    - uses: actions/upload-artifact@v3
      with:
        path: dist_exe/*

  PyPi:

    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Create virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
    - name: Install dependencies
      run: |
        python -m pip install .[release]

    - name: Get version
      uses: maybe-hello-world/pyproject-check-version@v4
      id: getversion
      with:
        pyproject-path: "./pyproject.toml"

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.getversion.outputs.local_version }}
        release_name: Release ${{ steps.getversion.outputs.local_version }}
        body: |
          GameArt ${{ steps.getversion.outputs.local_version }}
        draft: false
        prerelease: false

    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
